MyShoppingApp/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyShoppingApp.Models
{
    public class Cart
    {

        public int CartId { get; set; }

        public int VariantId { get; set; }
        public string PersonId { get; set; }
        public int Count { get; set; }
        public int TotalPrice { get; set; }

        [ForeignKey("VariantId")]
        public virtual  Variant Variant{ get; set; }

        [ForeignKey("PersonId")]
        public virtual Person Person { get; set; }
    }
}

MyShoppingApp/Controllers/CartController.cs
using MyShoppingApp.DAL;
using MyShoppingApp.Models;
using MyShoppingApp.ViewModels;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace MyShoppingApp.Controllers
{
    public class CartController : Controller
    {
        private ProductDb db = new ProductDb();

        // GET: Cart
        public ActionResult ShowCart()
        {
            if (Session["EmailId"] == null)
            {
                return RedirectToAction("MessageDetails");
            }

            List<VariantViewModel> ListVarient = (new SelectedDataList()).GetSelected();
            

            return View("AddProducts",ListVarient);
        }

        public ActionResult MessageDetails()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddProducts()
        {

            List<VariantViewModel> CheckedList = (List<VariantViewModel>)TempData["CheckedList"];


            

            UpdateDbClass obj = new UpdateDbClass();
            obj.UpdateDb(CheckedList, Session["EmailId"].ToString());
            
            List<VariantViewModel> Listvartient = (new SelectedDataList()).GetSelected();


            return View(Listvartient);
        }

        public ActionResult Remove(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart variant = db.Carts.Find(Id);
            if (variant == null)
            {
                return HttpNotFound();
            }
           
            db.Carts.Remove(variant);
            db.SaveChanges();
            
            return RedirectToAction("ShowCart");
        }

    }
}

MyShoppingApp/Controllers/CheckOutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyShoppingApp.DAL;
using MyShoppingApp.Models;
using MyShoppingApp.ViewModels;

namespace MyShoppingApp.Controllers
{
    public class CheckOutController : Controller
    {
        private ProductDb db = new ProductDb();

        // GET: CheckOut
        public ActionResult Index()
        {
            var cartObj = db.Carts;

            List<VariantViewModel> Listvartient = new List<VariantViewModel>();

            foreach (var items in cartObj)
            {
                var objVVM = new VariantViewModel();

                var id = items.VariantId;
                var ThatVarient = db.Variants.Find(id);

                objVVM.Image = ThatVarient.Product.Image;
                objVVM.Name = ThatVarient.Product.Name;
                objVVM.Description = ThatVarient.Product.Description;
                objVVM.Category = ThatVarient.Product.Category;
                objVVM.Size = ThatVarient.Size;
                objVVM.Color = ThatVarient.Color;
                objVVM.Price = ThatVarient.Price;
                objVVM.Count = items.Count;
                objVVM.TotalPrice = items.TotalPrice;
                objVVM.CartId = items.CartId;

                Listvartient.Add(objVVM);
            }

            return View(Listvartient);
        }

        public ActionResult Message(string Address)
        {

            int total = 0;
            foreach (var variant in db.Carts)
            {
                if (variant.PersonId.Equals(Session["EmailId"].ToString()))
                {
                    total = total + variant.TotalPrice;
                }
            }
            Order CurrOrder = new Order();

            CurrOrder.PersonId = Session["EmailId"].ToString();
            CurrOrder.Address = Address;
            CurrOrder.TotalAmount = total;

            db.Orders.Add(CurrOrder);
            db.SaveChanges();

            int rowno=0;
            foreach(var order in db.Orders)
            {
                rowno = order.OrderId;
            }

            //foreach (var variant in db.Carts)
            //{
            var results = (from a in db.Carts select a).ToList();
            foreach (var variant in results)
            {
                if (variant.PersonId.Equals(Session["EmailId"].ToString()))
                {
                    OrderedProduct p = new OrderedProduct();
                    p.VariantId = variant.VariantId;

                    p.OrderId = rowno;

                    p.Quantity = variant.Count;

                    db.OrderedProducts.Add(p);

                    db.SaveChanges();
                }

            }


            foreach (var variant in results)
            {
                if (variant.PersonId.Equals(Session["EmailId"].ToString()))
                {
                    db.Carts.Remove(variant);
                    db.SaveChanges();
                }
                
            }
            
            return View();
        }


        
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyShoppingApp/Views/Cart/AddProducts.cshtml
@using MyShoppingApp.Models
@using MyShoppingApp.ViewModels
@model List<MyShoppingApp.ViewModels.VariantViewModel>

@{
    ViewBag.Title = "Cart Page";
}

<h2>Your Cart:-</h2>

<table class="table">
    <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Description</th>
        <th>Category</th>
        <th>Size</th>
        <th>Color</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total Price</th>
    </tr>
    

    @foreach (var item in Model)
    {

       

        <tr>
            <td>
                <img src="@Url.Content(item.Image)" style="height:200px;width:200px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPrice)
            </td>
            <td>
                @Html.ActionLink("Remove", "Remove", "Cart", new { Id = item.CartId}, null)
            </td>
        </tr>
    }

</table>


    @using (Html.BeginForm("Index", "CheckOut", FormMethod.Get))
    {
        <p>
            <input type="submit" id="productSearch" value="Proceed To CheckOut" />
        </p>
    }

MyShoppingApp/Views/Cart/MessageDetails.cshtml
@{
    ViewBag.Title = "MessageDetails";
}

<h2>You need to login first to see your cart.</h2>

MyShoppingApp/Views/Cart/ShowCart.cshtml
@using MyShoppingApp.Models
@using MyShoppingApp.ViewModels
@model List<MyShoppingApp.ViewModels.VariantViewModel>

@{
    ViewBag.Title = "Show Cart Page";
}

<h2>Current Cart</h2>

<table class="table">
    <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Description</th>
        <th>Category</th>
        <th>Size</th>
        <th>Color</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total Price</th>
    </tr>

    @foreach (var item in Model)
    {

        

    <tr>
        <td>
            <img src="@Url.Content(item.Image)" style="height:200px;width:200px;" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Count)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            @Html.ActionLink("Remove", "Remove", "Cart", new { Id = item.CartId}, null)
        </td>
    </tr>
        }
    }

</table>